image: ubuntu:24.04

stages:
  - build
  - test
  - coverage

variables:
  BUILD_DIR: build

before_script:
  - export DEBIAN_FRONTEND=noninteractive
  - apt-get update -qq
  - apt-get install -qq -y build-essential cmake libomp-dev libopenmpi-dev openmpi-bin git lcov
  - lcov --version

build_project:
  stage: build
  script:
    - mkdir -p $BUILD_DIR && cd $BUILD_DIR
    - cmake -DENABLE_COVERAGE=ON -DWITH_TESTS=ON -DCMAKE_BUILD_TYPE=Debug ..
    - make -j$(nproc)
  artifacts:
    paths:
      - $BUILD_DIR
    expire_in: 1 hour

test_project:
  stage: test
  script:
    - cd $BUILD_DIR
    - ctest --output-on-failure

generate_coverage:
  stage: coverage
  script:
    - cd $BUILD_DIR
    - make coverage
  artifacts:
    paths:
      - $BUILD_DIR/coverage
    when: always
  coverage: '/lines.*: ([0-9]+\.[0-9]+)%/'
