#pragma once
#include <vector>
#include <numeric>
#include <algorithm>
#include <limits>
#include <mpi.h>
#include "body.h"
#include "morton_keys.h"

/**
 * @brief Sorts all local bodies data arrays in place based on their Morton key order
 *
 * To maintain data consistency, this function takes a permutation generated by sorting
 * the Morton keys and applies it to all corresponding particle attribute arrays (position,
 * mass, velocity, ID, etc.).
 *
 * @param[in,out] mortonData The Morton keys and normalized positions to be sorted.
 * @param[in,out] positions The positions vector to be sorted in parallel.
 * @param[in,out] masses The masses vector to be sorted in parallel.
 * @param[in,out] velocities The velocities vector to be sorted in parallel.
 * @param[in,out] ids The ID vector to be sorted in parallel.
 */
inline void  sortBodiesByMortonKey(
    std::vector<uint64_t>& mortonCodes,
    std::vector<Position>& pos,
    std::vector<double>&   mass,
    std::vector<Velocity>& vel,
    std::vector<uint64_t>& ids)
{
    const size_t N = pos.size();
    if (N == 0) return;

    std::vector<size_t> sort_idx(N);
    std::iota(sort_idx.begin(), sort_idx.end(), 0);

    std::sort(sort_idx.begin(), sort_idx.end(), [&](size_t a, size_t b) {
        return mortonCodes[a] < mortonCodes[b];
    });

    auto permute = [&](auto &vec) {
        std::vector<std::decay_t<decltype(vec[0])>> tmp(vec.size());
        for (size_t i = 0; i < vec.size(); ++i) tmp[i] = vec[sort_idx[i]];
        vec.swap(tmp);
    };

    // Permute all data arrays to match the sorted key order
    permute(pos);
    permute(mass);
    permute(vel);
    permute(ids);
    permute(mortonCodes);
}
